main: me.cryptidyy.oceanraiders.Main
name: OceanRaiders-1.21
version: 1.0
author: cryptidyy
api-version: 1.21

depend: [CoreAPI, FriendsAPIForPartyAndFriends, Spigot-Party-API-PAF]

commands:
  orsetup:
  oceanraiders:
  ortest:
  setstate: